export const POPULATE_ENTRIES = 'POPULATE_ENTRIES';
export const ADD_ENTRY = 'ADD_ENTRY';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const CHANGE_ENTRY_END = 'CHANGE_ENTRY_END';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const START_DRAG_ENTRY_END = 'START_DRAG_ENTRY_END';
export const SET_DRAG_START = 'SET_DRAG_START';
export const END_DRAG_ENTRY_END = 'END_DRAG_ENTRY_END';
export const DRAG_MOVE_ENTRY_END = 'DRAG_MOVE_ENTRY_END';
